### ISSUE TITLE
tcpdf.php on line 2465 : Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by GregorBaiker** [contao/tcpdf-bundle#4]
PHP: 8.2
Contao : 4.13.28
PDF-Artikel : 1.2.2
tecnickcom/tcpdf : 6.6.2

**I get a lot of following errors/warnings in log:**

domain.xx [Sun Aug 06 13:11:21.490907 2023] [-:warn] [pid 22624:tid 140552762763008] [client 66.249.66.164:0] FastCGI: too much stderr received from server "/home/clients/.../.config/apache/domain.xx/.fpm/php5.external", increase **FCGI_SERVER_MAX_STDERR_LINE_LEN (1023)** and rebuild or use "\\n" to terminate lines

domain.xx [Sun Aug 06 13:11:21.490904 2023] [-:error] [pid 22624:tid 140552762763008] [client 66.249.66.164:0] FastCGI: server "/home/clients/.../.config/apache/domain.xx/.fpm/php5.external" stderr: 

sattzeitung.org/vendor/tecnickcom/tcpdf/tcpdf.php on line 2465; PHP message: PHP Warning: Trying to access array offset on value of type null in /home/clients/.../sites/domain.xx/vendor/tecnickcom/tcpdf/**tcpdf.php** on line 2465; PHP message: PHP Warning: Trying to access array offset on value of type null in /home/clients/.../sites/domain.xx/vendor/tecnickcom/tcpdf/**tcpdf.php** on line 2465; PHP message: PHP Warning: Trying to access array offset on value of type null in /home/clients/.../sites/domain.xx/vendor/tecnickcom/tcpdf/**tcpdf.php** on line 2465; PHP message: PHP Warning: Trying to access array offset on value of type null in /home/clients/.../sites/domain.xx/vendor/tecnickcom/tcpdf/**tcpdf.php** on line 2465; PHP message: PHP Warning: Trying to access array offset on value of type null in /home/clients/.../sites/domain.xx/vendor/t

Can you check, whether it is a bug?
Thanks a lot!

**Comment by ausi** [comment]
This seems to be a problem in `tecnickcom/tcpdf` itself I think. You’d need to debug why `$this->cell_padding` is `NULL` here: https://github.com/tecnickcom/TCPDF/blob/2fb1c01bc37487d1f94fe1297f8d8ad1b5c290bb/tcpdf.php#L2465
